#!/bin/bash
repo_cfg="${HOME}/.github"
repo_find() { grep "$1" $repo_cfg | awk '{ print $2 }'; }
root_find() { grep "$1" $repo_cfg | awk '{ print $1 }'; }
repo_add() { echo "${1} ${2}" >> $repo_cfg; }

tmpdir="/tmp/github-$$"
test -d $tmpdir || mkdir $tmpdir
cleanup() { rm -rf $tmpdir; }
die() { echo "$@"; exit 1; }
trap cleanup EXIT

repo_init() {
	dirent="$1"
	repo="$2"

	grep -qs $repo $repo_cfg && { 
		die "repo already exists: $repo"
	}
	repo_add ${PWD}/$dirent $repo

	! git clone $repo $tmpdir 2>&1 | grep -qs 'empty repository'  && { 
		die "remote repo already exists: $repo"
	}
	cp -r $dirent $tmpdir
	(
		cd $tmpdir
		git init 
		git add *
		git commit -m initial -a
		git push -u origin master
	)
	exit 0
}

repo_push() {
	dirent="$1"
	repo=$( repo_find $PWD )
	root=$( root_find $PWD )
	rel=${PWD##$root}
	[[ ${#PWD} -lt ${#root} ]] && rel="."

	git clone -q $repo $tmpdir
	git_add=""
	[[ ! -e ${tmpdir}/${rel}/${dirent} ]] && git_add=1
	cp -r $dirent ${tmpdir}/${rel}/.
	( 
		cd $tmpdir
		[[ "$git_add" != "" ]] && git add ${rel}/${dirent}
		git commit -m 'trivial change' -a
		git push -q origin master
	)
}

[[ "$1" = "" ]] && { #n00b
cat<<EOF
To init a remote repo:
	$0 DIR github_repo 
To push to the repo
	$0 push FILE
To pull from the repo
	$0 pull 
EOF
}

[[ -e "$1" && "$2" != "" ]] && repo_init $1 $2

[[ $1 = "push" && -e "$2" ]] && repo_push $2
